version: '3'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
    nginx:
        build: nginx
#        ports:
#            - 80:80
#        volumes_from:
#            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
        environment:
            VIRTUAL_HOST: docker1.elijahoyekunle.com
            LETSENCRYPT_HOST: docker1.elijahoyekunle.com
            LETSENCRYPT_EMAIL: eloyekunle@gmail.com
        expose:
            - "80"
            - "443"
    elk:
        build: 'https://github.com/playmice/docker-elk.git'
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash/conf.d
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
            - ./logs/nginx/:/var/log/nginx
#        volumes_from:
#            - php
#            - nginx

networks:
  default:
    external:
      name: nginx-proxy